services:
  my-app:
    image: belalelnady/solution-plus
    container_name: u-container 
    environment:
      - APP_ENV=${APP_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    ports:
      - "4040:${PORT}"
    networks:
      - app-network
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0.41
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dbModel/schema.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./dbModel/initialize.sql:/docker-entrypoint-initdb.d/1_init.sql



networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
